### ISSUE TITLE
mac and linux give different mediainfo output

### ISSUE THREAD

**Issue by mcampos-quinn** [BAM-PFA/pymm#1]
As tested on Ubuntu 16.04 the mediainfo tags are as such:

```
<Mediainfo>
<File>
<track type='whatever'>
```

and on Sierra it's

```
<MediaInfo>
<media>
<track type='bla bla bla'>
```

Find a way to even out this discrepancy in code that is hard coded to expect a certain format (now only concatFiles.py).

**Comment by kieranjol** [comment]
Sounds like you need to update mediainfo on Ubuntu as it's using the old mediainfo schema?

**Comment by JeromeMartinez** [comment]
Mac and Linux give same MediaInfo output, issue is the version of the tools you use, the default XML format has changed since MediaInfo 17.10.
You can use [`--Output=OldXML`](https://github.com/MediaArea/MediaInfoLib/blob/6a895f57e8318ac112a59cb092928ecbfc47986f/History_DLL.txt#L14) with 17.10+ versions if you want the old behavior.

**Comment by mcampos-quinn** [comment]
Thanks @kieranjol and @JeromeMartinez ! I assumed that this was a version discrepancy.  I was doing some testing after putting the baby to bed last night.... 

I updated MediaInfo on Ubuntu and returned the expected (new) schema.
