### ISSUE TITLE
mediainfo pbcore2 output on dpx folder is wonky

### ISSUE THREAD

**Issue by mcampos-quinn** [BAM-PFA/pymm#20]
So when you run `mediainfo --Output=PBCore2 /path/2/dpx/dir` you get a neat output that is basically a summary of what's in the folder. 

BUT you don't get valid XML back. you get two half-valid XML bits. The first is general summary stuff and the second is more detailed information taken from a (randomly selected?) file within the directory. This means that my parsing of the XML PBCore output from `mediainfo` is only able to recognize the first half.

Since the stuff we care about is mostly in the second bit (details like pixel dimensions, and some other stuff) I made a mod to look for the first file in the directory and use that as the basis to represent the entire sequence folder. 

I want to revisit this later and look more closely at what this means.

**Comment by mcampos-quinn** [comment]
Running the same on another Mac with 18.05 and correct output makes me suspect my Ubuntu build/apt repository/something else.

Filed a bug report w mediaarea last week anyway.

**Comment by kieranjol** [comment]
Pbcore2 output is indeed different between 18.03 and 18.05,to the point
where it breaks some of our scripts. I parse the PBCore XML and generate an
importable CSV from that,but I should have done this with the `-f
--Language=raw --Output=OLDXML` as it's a bit more stable.
I haven't been using it with dpx but there could have been some unexpected
changes after the update.

**Comment by mcampos-quinn** [comment]
:/
I am taking the instantiation/essence track chunk out of the mediainfo output and adding each instantiation to an XML record for the work (or the **manifestation** in FRBR/FIAF talk) as a whole. So for the most part, changes (like changing which tag a bit of information is contained in) are not a huge deal, but for whatever reason on Ubuntu the XML output is not actually valid XML, which breaks my script. Or actually it just leaves out everything past the invalid elements. I found a workaround but I feel less secure with it.

Run on an image sequence folder the mediainfo output is kind of cool! It peeks inside and gives you a snapshot of the sequence including start and end frame numbers and all the embedded metadata, color information, etc. 

Hopefully Jerome and co. will have some kind of answer?

**Comment by JeromeMartinez** [comment]
I think there are 2 different issues there:
- the DPX sequence is not detected on Ubuntu so several files are analyzed. I think this [is due to unsorted output from Ubuntu 16.04 as we faced with RAWcooked project](https://github.com/MediaArea/RAWcooked/pull/99). I imagine that I need to implement same on MediaInfo.
- the PBCore2 output does not support well several files in input, it was designed for a single file, so there is 1 PBCore2 output per file. We don't plan to change that for the moment, at least on free support.

**Comment by mcampos-quinn** [comment]
@JeromeMartinez thank you so much for that information! Yes I found that the sorting on Ubuntu for DPX sequences (in another context of this project) was unreliable. I think that even though it isn't 'supposed' to work PBCore2 output on a DPX directory produces an result that is actually handy. I can close this issue, but we now know that if it's something we need to pursue we will try to seek paid support.

**Comment by JeromeMartinez** [comment]
Misunderstanding: for the first point (sorting), [it is on the way](https://github.com/MediaArea/MediaInfoLib/pull/963), check [snapshots](https://mediaarea.net/download/snapshots/binary/) tomorrow.
The second point may be there again if you e.g. have a WAV file in the directory, which will not be caught with the DPX for being a single package so 2 PBCore2 outputs in 1 shot instead of 1 PBCore output with video and audio together, I think it could be relevant to sponsor such kind of development in order to have a PBCore2 output corresponding to the expected view from the user i.e. video and audio in 1 package.
